userPath:
passPath:
#timeout: 3
url: http://natas17:XkEuChE0SbnKBvH1RU7ksIb9uuLmI7sd@natas17.natas.labs.overthewire.org/index.php
#url: http://natas17.natas.labs.overthewire.org/index.php
method: POST
header:
  Content-Type: application/x-www-form-urlencoded
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
  # Authentication: Basic
body:
  username:
  password: